server:
  port: 8085

spring:
  application:
    name: streamcell

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    root: INFO
    com.streamcell: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

springdoc:
  packages-to-scan: com.streamcell.platform
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
