server:
  port: 8085

spring:
  application:
    name: streamcell

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

flink:
  base-url: ${FLINK_JOB_MANAGER_URL}
  
file:
  upload:
    dir: C:\streamcell_workspace\upload
    custom-jar-path: C:\streamcell_workspace\upload\flink\artifacts

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/mapper/**/*.xml
  type-handlers-package: com.streamcell.global.helper.typehandler

logging:
  level:
    root: INFO
    com.streamcell: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

springdoc:
  packages-to-scan: com.streamcell.platform
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    doc-expansion: none

jwt:
  secret-key: 1baaf8271e1345245b0bc65f414d00d4d3cf3ac109e671f376fd233b28b48c37e7cf976cd6adb03214ec552b4c284bbae97f3c1e2eba9a1a4a9c3562d002c584
  refresh-key: e0243e8635ab32136c9f45aa981d9b99dbe637584ddd2b45588929eb0aa8c18919529f5f776e204050e3c05016c8f025c468b6aa9b35f1781814501b23ccfaae